export const scoreExplanations:Record<string,{tone:"support"|"risk"|"context";label:string}>={
  VALUE_STRONG:{tone:"support",label:"Strong relative valuation evidence"},
  VALUE_WEAK:{tone:"risk",label:"Weak relative valuation evidence"},
  QUALITY_STRONG:{tone:"support",label:"Strong profitability and growth evidence"},
  QUALITY_WEAK:{tone:"risk",label:"Weak or deteriorating quality evidence"},
  MOMENTUM_RISK_HIGH:{tone:"risk",label:"Elevated momentum risk"},
  MARKET_RISK_HIGH:{tone:"risk",label:"Elevated volatility or drawdown risk"},
  BALANCE_SHEET_RISK_HIGH:{tone:"risk",label:"Elevated balance-sheet risk"},
  EVIDENCE_SPARSE:{tone:"risk",label:"Insufficient feature evidence"},
  EVIDENCE_PARTIAL:{tone:"context",label:"Partial feature coverage"},
  EVIDENCE_COMPLETE:{tone:"context",label:"Nearly complete feature coverage"},
  GROWTH_SPURT_DETECTED:{tone:"context",label:"Recent historical price path matches the Growth Spurt detector"},
  GROWTH_SPURT_EMERGING:{tone:"context",label:"Recent upward trend is emerging but below full detection threshold"},
  TREND_SLOPE_STRONG:{tone:"context",label:"Positive 63-session trend slope"},
  TREND_CONSISTENCY_STRONG:{tone:"context",label:"Price path stayed close to the fitted trend line"},
  MARKET_RELATIVE_STRENGTH:{tone:"context",label:"Recent return exceeded SPY over the detector window"},
  LOW_TREND_DRAWDOWN:{tone:"context",label:"Recent trend had limited drawdown"},
  RECENT_TREND_CONFIRMED:{tone:"context",label:"Recent 21-session movement confirms the longer trend"},
  TREND_TOO_VOLATILE:{tone:"risk",label:"Recent price path was too volatile for a clean Growth Spurt tag"},
  ONE_DAY_SPIKE_DOMINATED:{tone:"risk",label:"A single trading day explains too much of the recent move"},
  TREND_HISTORY_INSUFFICIENT:{tone:"risk",label:"Insufficient price history for the Growth Spurt detector"},
  TREND_WEAK_RELATIVE_TO_MARKET:{tone:"risk",label:"Recent trend was weak relative to SPY"},
};
