import type { CSSProperties } from "react";
import type { BacktestData } from "@/lib/etl";

const percent=(value:number)=>`${value>=0?"+":""}${(value*100).toFixed(2)}%`;

export function BacktestResults({data}:{data:BacktestData}){
  const cohorts=data.cohorts.filter(row=>row.marketRegime==="all");
  if(data.status!=="complete"||!cohorts.length)return <section className="backtest-awaiting" role="status"><p className="eyebrow">RESULT STATUS</p><h2>Awaiting a valid historical cohort</h2><p>ValueSignal will not backfill today’s score into the past. The next live ETL must reconstruct snapshots from prices and filings that were available on each signal date before results can be displayed.</p><ul>{data.biasAudit.notes.map(note=><li key={note}>{note}</li>)}</ul></section>;
  return <section className="backtest-results"><div className="section-head"><div><p className="eyebrow">COHORT RESULTS</p><h2>Signal usefulness by horizon</h2></div><p>Excess return compares each observation with SPY over exactly aligned entry and outcome dates.</p></div><div className="backtest-bars">{cohorts.map(row=>{const size=Math.min(Math.abs(row.meanExcessReturn)*500,50);return <article key={`${row.signal}-${row.horizonSessions}`}><div><strong>{row.signal.replaceAll("-"," ")}</strong><span>{row.horizonSessions} sessions · n={row.sampleCount}</span></div><div className="return-axis"><i className={row.meanExcessReturn>=0?"positive":"negative"} style={{"--bar-size":`${size}%`} as CSSProperties}/></div><b className={row.meanExcessReturn>=0?"up":"down"}>{percent(row.meanExcessReturn)}</b></article>})}</div><div className="table-shell backtest-table"><table><caption className="sr-only">Backtest cohort metrics and sample sizes</caption><thead><tr><th>Signal / horizon</th><th>Sample</th><th>Forward</th><th>Benchmark</th><th>Excess 95% interval</th><th>Win rate</th><th>Adverse drawdown</th></tr></thead><tbody>{cohorts.map(row=><tr key={`${row.signal}-${row.horizonSessions}`}><td>{row.signal.replaceAll("-"," ")} / {row.horizonSessions}d</td><td>{row.sampleCount}</td><td>{percent(row.meanForwardReturn)}</td><td>{percent(row.meanBenchmarkReturn)}</td><td>{row.excessReturnConfidenceInterval95?row.excessReturnConfidenceInterval95.map(percent).join(" to "):"—"}</td><td>{(row.winRate*100).toFixed(1)}%</td><td>{percent(row.meanAdverseDrawdown)}</td></tr>)}</tbody></table></div></section>;
}
