"use client";

import {useState,type FormEvent} from "react";
import type {FilingEvidence} from "@/lib/search";

const prompts=["risk factors","supply chain","liquidity and debt","cybersecurity"];

export function FilingEvidencePanel({ticker,initialResults}:{ticker:string;initialResults:FilingEvidence[]}){
  const [query,setQuery]=useState("risk factors");const [results,setResults]=useState(initialResults);const [loading,setLoading]=useState(false);const [searched,setSearched]=useState(Boolean(initialResults.length));
  async function search(event?:FormEvent,override?:string){event?.preventDefault();const value=(override??query).trim();if(value.length<2)return;setQuery(value);setLoading(true);setSearched(true);try{const response=await fetch(`/api/search?ticker=${encodeURIComponent(ticker)}&q=${encodeURIComponent(value)}`);const payload=await response.json() as {results:FilingEvidence[]};setResults(payload.results??[])}finally{setLoading(false)}}
  return <section className="filing-evidence"><div className="section-head"><div><p className="eyebrow">RETRIEVED SEC EVIDENCE</p><h2>Search the filings</h2></div><p>Passages below are source text ranked by BM25. They are kept separate from ValueSignal’s quantitative analysis.</p></div><form onSubmit={search} className="evidence-search" role="search"><label><span className="sr-only">Search {ticker} filings</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search risks, liquidity, competition…"/></label><button type="submit" disabled={loading}>{loading?"Searching…":"Search filings"}</button></form><div className="query-prompts" aria-label="Suggested filing searches">{prompts.map(prompt=><button type="button" key={prompt} onClick={()=>void search(undefined,prompt)}>{prompt}</button>)}</div>{results.length?<div className="evidence-results">{results.map(result=><article key={result.id}><header><div><strong>{result.form} · {result.item}</strong><span>Filed {result.filingDate} · Accession {result.accession}</span></div><b>BM25 {result.score.toFixed(2)}</b></header><blockquote>{result.text}</blockquote><div className="citation-row"><span>Matched: {result.matchedTerms.join(", ")}</span><a href={result.url} target="_blank" rel="noreferrer">Open filing citation ↗</a></div></article>)}</div>:<div className="evidence-empty" role="status"><h3>{searched?"No matching passage found.":"The filing index is awaiting its first refresh."}</h3><p>{searched?"Try a broader term or inspect the filing directly after the index refresh.":"The scheduled SEC retrieval job will populate cited 10-K and 10-Q passages."}</p></div>}</section>;
}
